spring:
  application:
    name: spring-boot-rabbit-stream-producer
server:
  tomcat:
    threads:
      min: 10 # Minimum amount of worker threads. default 10
      max: 100 # dMaximum amount of worker threads. default 100